import type { Bursary } from "@/lib/types";

export const verifiedBursaries: Bursary[] = [
  {
    id: "nsfas-2026",
    name: "NSFAS Funding",
    provider: "National Student Financial Aid Scheme",
    fieldOfStudy: "All fields / financial aid",
    fundingType: "financial aid",
    studyLevels: ["undergraduate", "TVET"],
    eligibilityCriteriaJson: [
      "South African citizen or permanent resident",
      "Means-tested household income",
      "Public university or TVET college"
    ],
    minAverage: 0,
    minSubjectRequirementsJson: [],
    provinceRequirements: ["All provinces"],
    citizenshipRequirements: "South African citizen or permanent resident",
    deadline: "",
    officialStatus: "unknown",
    applicationUrl: "https://www.nsfas.org.za/content/how-to-apply.html",
    requiredDocumentsJson: ["South African ID", "Parent/guardian and household income details", "Supporting documents requested in the portal"],
    sourceUrl: "https://www.nsfas.org.za/content/how-to-apply.html",
    lastVerifiedAt: "2026-06-08",
    lastCheckedAt: "2026-06-08",
    summary: "Means-tested funding for eligible students at public universities and TVET colleges.",
    applicationWindow: "Apply through the myNSFAS portal when the cycle is open.",
    notes: "Check the portal for the current intake before applying."
  },
  {
    id: "funza-lushaka-2026",
    name: "Funza Lushaka Bursary",
    provider: "Department of Basic Education",
    fieldOfStudy: "Education / Teaching",
    fundingType: "bursary",
    studyLevels: ["undergraduate", "initial teacher education"],
    eligibilityCriteriaJson: [
      "First-time applicants must be 30 years or younger",
      "Initial teacher education",
      "South African citizen"
    ],
    minAverage: 60,
    minSubjectRequirementsJson: [{ subject: "Mathematics", minMark: 50 }],
    provinceRequirements: ["All provinces"],
    citizenshipRequirements: "South African citizen",
    deadline: "2026-02-01",
    officialStatus: "closed",
    applicationUrl: "https://www.eservices.gov.za/FunzaLushaka/",
    requiredDocumentsJson: ["Certified ID copy", "Academic record", "Teacher education application details"],
    sourceUrl: "https://www.funzalushaka.doe.gov.za/",
    lastVerifiedAt: "2026-06-08",
    lastCheckedAt: "2026-06-08",
    summary: "Teacher training bursary for students preparing for initial teacher education.",
    applicationWindow: "2026 applications opened 7 October 2025 and closed 1 February 2026.",
    notes: "Use the e-Gov portal and follow the application steps on the official page."
  },
  {
    id: "csir-sasol-foundation",
    name: "CSIR-Sasol Foundation Bursary",
    provider: "CSIR and Sasol Foundation",
    fieldOfStudy: "Engineering / Science / Technology",
    fundingType: "bursary",
    studyLevels: ["undergraduate"],
    eligibilityCriteriaJson: [
      "South African citizen",
      "Full-time study at a public university",
      "Priority STEM field"
    ],
    minAverage: 65,
    minSubjectRequirementsJson: [
      { subject: "Mathematics", minMark: 70 },
      { subject: "Physical Sciences", minMark: 70 }
    ],
    provinceRequirements: ["All provinces"],
    citizenshipRequirements: "South African citizen",
    deadline: "",
    officialStatus: "unknown",
    applicationUrl: "https://www.csir.co.za/careers/students-graduates/bursaries/sasol-foundation-bursary",
    requiredDocumentsJson: ["Updated CV", "Certified ID copy", "Latest academic record", "Grade 11 final results"],
    sourceUrl: "https://www.csir.co.za/careers/students-graduates/bursaries/sasol-foundation-bursary",
    lastVerifiedAt: "2026-06-08",
    lastCheckedAt: "2026-06-08",
    summary: "Comprehensive bursary for priority STEM study areas at South African public universities.",
    applicationWindow: "Check the CSIR bursary page for the current intake.",
    notes: "The official page lists priority fields and the current documents required."
  },
  {
    id: "firstrand-bursaries",
    name: "FirstRand Bursaries",
    provider: "FirstRand",
    fieldOfStudy: "Accounting / Data / Actuarial / Engineering",
    fundingType: "bursary",
    studyLevels: ["second-year undergraduate", "postgraduate"],
    eligibilityCriteriaJson: [
      "South African citizen",
      "Strong academic performance",
      "Selected quantitative or CA-focused fields"
    ],
    minAverage: 65,
    minSubjectRequirementsJson: [],
    provinceRequirements: ["All provinces"],
    citizenshipRequirements: "South African citizen",
    deadline: "2026-01-30",
    officialStatus: "closed",
    applicationUrl: "https://www.start.firstrand.co.za/Home/Bursaries",
    requiredDocumentsJson: ["CV", "Academic record", "Motivation letter"],
    sourceUrl: "https://www.start.firstrand.co.za/Home/Bursaries",
    lastVerifiedAt: "2026-06-08",
    lastCheckedAt: "2026-06-08",
    summary: "Bursaries from second year onward for selected quantitative and CA-focused study paths.",
    applicationWindow: "2026 applications opened 4 November 2025 and closed 30 January 2026.",
    notes: "The official page lists bursaries from second year onward for selected streams."
  },
  {
    id: "nedbank-bursary-programme",
    name: "Nedbank Bursary Programme",
    provider: "Nedbank",
    fieldOfStudy: "Finance / Banking / Scarce skills",
    fundingType: "bursary",
    studyLevels: ["undergraduate", "postgraduate"],
    eligibilityCriteriaJson: [
      "South African citizen",
      "At least 65% average",
      "Meets university registration criteria",
      "Degree matches a scarce skill"
    ],
    minAverage: 65,
    minSubjectRequirementsJson: [],
    provinceRequirements: ["All provinces"],
    citizenshipRequirements: "South African citizen",
    deadline: "",
    officialStatus: "unknown",
    applicationUrl: "https://jobs.nedbank.co.za/go/Bursary-Programme/4161701/",
    requiredDocumentsJson: ["Academic record", "Proof of financial need", "ID document"],
    sourceUrl: "https://jobs.nedbank.co.za/go/Bursary-Programme/4161701/",
    lastVerifiedAt: "2026-06-08",
    lastCheckedAt: "2026-06-08",
    summary: "Funding for students studying toward degrees that support scarce skills at Nedbank and in South Africa.",
    applicationWindow: "Check the Nedbank bursary portal for the live application status.",
    notes: "The job portal page describes the qualification questions used in screening."
  },
  {
    id: "studytrust-bursaries",
    name: "StudyTrust Bursaries and Scholarships",
    provider: "StudyTrust",
    fieldOfStudy: "Multiple fields",
    fundingType: "bursary / scholarship",
    studyLevels: ["undergraduate", "postgraduate", "TVET"],
    eligibilityCriteriaJson: [
      "South African citizen",
      "Sponsor-specific criteria apply",
      "One application can be considered for multiple bursaries"
    ],
    minAverage: 0,
    minSubjectRequirementsJson: [],
    provinceRequirements: ["All provinces"],
    citizenshipRequirements: "South African citizen",
    deadline: "2026-09-30",
    officialStatus: "open",
    applicationUrl: "https://studytrust.org.za/bursary-applications/",
    requiredDocumentsJson: ["Academic record", "ID document", "Supporting documents requested by the sponsor"],
    sourceUrl: "https://studytrust.org.za/bursary-applications/",
    lastVerifiedAt: "2026-06-08",
    lastCheckedAt: "2026-06-08",
    summary: "One application can be considered for multiple sponsor-funded bursaries.",
    applicationWindow: "Most sponsor bursaries close on 30 September.",
    notes: "Use the StudyTrust application portal to be considered for eligible sponsor bursaries."
  },
  {
    id: "thuthuka-bursary-fund",
    name: "Thuthuka Bursary Fund",
    provider: "SAICA",
    fieldOfStudy: "Accounting",
    fundingType: "bursary",
    studyLevels: ["undergraduate"],
    eligibilityCriteriaJson: [
      "South African citizen",
      "Black African or Coloured",
      "BCom Accounting CA-stream",
      "Must write the NBT"
    ],
    minAverage: 60,
    minSubjectRequirementsJson: [{ subject: "Mathematics", minMark: 60 }],
    provinceRequirements: ["All provinces"],
    citizenshipRequirements: "South African citizen",
    deadline: "",
    officialStatus: "unknown",
    applicationUrl: "https://www.thuthukabursaryfund.co.za/",
    requiredDocumentsJson: ["Certified ID copy", "Grade 11 results or matric results", "Household income details"],
    sourceUrl: "https://www.saica.org.za/initiatives/thuthuka/apply-to-the-thuthuka-bursary-fund/",
    lastVerifiedAt: "2026-06-08",
    lastCheckedAt: "2026-06-08",
    summary: "BCom Accounting bursary for students who want to become CAs(SA).",
    applicationWindow: "Apply through the official Thuthuka bursary portal.",
    notes: "The official SAICA page lists the core eligibility criteria and NBT requirement."
  },
  {
    id: "standard-bank-bursary",
    name: "Standard Bank Group Bursary",
    provider: "Standard Bank",
    fieldOfStudy: "Commerce / Finance / Technology",
    fundingType: "bursary",
    studyLevels: ["undergraduate", "postgraduate"],
    eligibilityCriteriaJson: [
      "South African citizen",
      "Average of at least 65%",
      "Full-time study",
      "Matches listed priority fields"
    ],
    minAverage: 65,
    minSubjectRequirementsJson: [],
    provinceRequirements: ["All provinces"],
    citizenshipRequirements: "South African citizen",
    deadline: "2025-09-30",
    officialStatus: "closed",
    applicationUrl: "https://www.standardbank.com/sbg/standard-bank-group/careers/early-careers/bursaries",
    requiredDocumentsJson: ["Academic record", "ID document", "Financial need details"],
    sourceUrl: "https://www.standardbank.com/sbg/standard-bank-group/careers/early-careers/bursaries",
    lastVerifiedAt: "2026-06-08",
    lastCheckedAt: "2026-06-08",
    summary: "Undergraduate and postgraduate bursary support in key commerce and technical fields.",
    applicationWindow: "2026 bursary season opened 1 May 2025 and closed 30 September 2025.",
    notes: "Standard Bank routes applications through the StudyTrust bursary fund."
  },
  {
    id: "transnet-bursary",
    name: "Transnet Bursary Programme",
    provider: "Transnet",
    fieldOfStudy: "Engineering / Logistics / Built environment",
    fundingType: "bursary",
    studyLevels: ["undergraduate"],
    eligibilityCriteriaJson: [
      "South African citizen",
      "Relevant engineering or built-environment field",
      "Meets Transnet study requirements"
    ],
    minAverage: 65,
    minSubjectRequirementsJson: [{ subject: "Mathematics", minMark: 60 }],
    provinceRequirements: ["All provinces"],
    citizenshipRequirements: "South African citizen",
    deadline: "",
    officialStatus: "unknown",
    applicationUrl: "https://bursaryconnect.transnet.net/",
    requiredDocumentsJson: ["Academic record", "ID document", "Motivation letter"],
    sourceUrl: "https://www.transnet.net/RenderPage.aspx?id=2701803",
    lastVerifiedAt: "2026-06-08",
    lastCheckedAt: "2026-06-08",
    summary: "Full-time bursary funding for selected degrees aligned to Transnet’s skills needs.",
    applicationWindow: "Apply through the official Transnet bursary system when applications are open.",
    notes: "The application system is separate from the public company page."
  }
];
